plugin: amazon.aws.ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags.Name
    prefix: tag_name_
hostnames:
  - tag:Name
compose:
  ansible_host: public_ip_address
  ansible_user: ec2-user
  ansible_ssh_private_key_file: /home/ec2-user/stack-automator-project.pem
filters:
  instance-state-name: running